# Generated by Django 4.2.29 on 2026-03-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_agency_address_agency_created_at_agency_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Komisyon Oranı (%)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Demo Acente'),
        ),
        migrations.AddField(
            model_name='agency',
            name='sub_merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Iyzico Sub-Merchant ID'),
        ),
        migrations.AddField(
            model_name='agency',
            name='tursab_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TURSAB No'),
        ),
    ]
