# Generated by Django 4.2.29 on 2026-04-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_add_business_type_menu_table_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='business_type',
            field=models.CharField(choices=[('acenta', 'Tur Acentası'), ('restoran', 'Restoran'), ('kafe', 'Kafe')], default='acenta', max_length=20, verbose_name='İşletme Türü'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='table_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Masa No (Serbest Metin)'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20, verbose_name='Masa Numarası/Adı')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Kapasite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kullanımda mı?')),
                ('restaurant', models.ForeignKey(limit_choices_to={'business_type': 'restoran'}, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='agencies.agency', verbose_name='Restoran')),
            ],
            options={
                'verbose_name': 'Masa',
                'verbose_name_plural': 'Masalar',
            },
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='agencies.table', verbose_name='Atanan Masa'),
        ),
    ]
