# Generated by Django 4.2.29 on 2026-05-14 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_alter_agency_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('status', models.CharField(choices=[('pending', 'İncelemede'), ('approved', 'Onaylandı'), ('paid', 'Ödendi'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Hakediş Talebi',
                'verbose_name_plural': 'Hakediş Talepleri',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentFinanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(max_length=50, unique=True)),
                ('tour_title', models.CharField(max_length=255)),
                ('tour_date', models.DateField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_type', models.CharField(choices=[('sale', 'Satış Hakedişi'), ('refund', 'İade Kesintisi'), ('adjustment', 'Manuel Düzeltme')], default='sale', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Finansal Kayıt',
                'verbose_name_plural': 'Finansal Kayıtlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agency', '-created_at'], name='agencies_ag_agency__332fe6_idx')],
            },
        ),
    ]
