# Generated by Django 4.2.29 on 2026-05-14 22:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_finance_ledger_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255, verbose_name='Misafir Adı')),
                ('guest_phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('guest_count', models.PositiveIntegerField(default=1, verbose_name='Kişi Sayısı')),
                ('table_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Masa No (Serbest Metin)')),
                ('reservation_date', models.DateField(verbose_name='Rezervasyon Tarihi')),
                ('reservation_time', models.TimeField(verbose_name='Saat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('confirmed', 'Onaylandı'), ('seated', 'Masaya Alındı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Tutar (₺)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Restoran Rezervasyonu',
                'verbose_name_plural': 'Restoran Rezervasyonları',
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='available_tables',
            field=models.PositiveIntegerField(default=10, verbose_name='Boş Masa Sayısı'),
        ),
        migrations.DeleteModel(
            name='TableReservation',
        ),
        migrations.AddField(
            model_name='diningreservation',
            name='restaurant',
            field=models.ForeignKey(limit_choices_to={'business_type': 'restoran'}, on_delete=django.db.models.deletion.CASCADE, related_name='dining_reservations', to='agencies.agency', verbose_name='Restoran'),
        ),
        migrations.AddField(
            model_name='diningreservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dining_reservations', to='agencies.table', verbose_name='Atanan Masa'),
        ),
    ]
