# Generated by Django 4.2.29 on 2026-05-14 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0009_restaurant_realtime_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image_sub1',
            field=models.ImageField(blank=True, null=True, upload_to='menus/', verbose_name='Görsel (Yan 1)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='image_sub2',
            field=models.ImageField(blank=True, null=True, upload_to='menus/', verbose_name='Görsel (Yan 2)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menus/', verbose_name='Görsel (Ana)'),
        ),
        migrations.CreateModel(
            name='MenuDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='menus/docs/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agencies.menu')),
            ],
        ),
    ]
