# Generated by Django 4.2.29 on 2026-07-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_menu_file_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hesap Sahibi'),
        ),
        migrations.AddField(
            model_name='agency',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banka Adı'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contract_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sözleşme Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='agency',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='agencies/covers/', verbose_name='Kapak Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='agency',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='agency',
            name='iban',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='agency',
            name='kvkk_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KVKK Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='agency',
            name='legal_entity_type',
            field=models.CharField(blank=True, choices=[('company', 'Şirket (Ltd./A.Ş.)'), ('individual', 'Şahıs İşletmesi')], max_length=20, null=True, verbose_name='Tüzel Kişilik Türü'),
        ),
        migrations.AddField(
            model_name='agency',
            name='mersis_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MERSİS No'),
        ),
        migrations.AddField(
            model_name='agency',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Kayıt Adımı'),
        ),
        migrations.AddField(
            model_name='agency',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Red / Eksik Bilgi Sebebi'),
        ),
        migrations.AddField(
            model_name='agency',
            name='status',
            field=models.CharField(choices=[('taslak', 'Taslak'), ('beklemede', 'Beklemede'), ('inceleniyor', 'İnceleniyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('eksik_bilgi', 'Eksik Bilgi')], default='taslak', max_length=20, verbose_name='Başvuru Durumu'),
        ),
        migrations.AddField(
            model_name='agency',
            name='tax_id',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Vergi Kimlik No / TCKN'),
        ),
        migrations.AddField(
            model_name='agency',
            name='tax_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='agency',
            name='trade_registry_document',
            field=models.FileField(blank=True, null=True, upload_to='agencies/legal/', verbose_name='Ticaret Sicil / Faaliyet Belgesi'),
        ),
        migrations.AddField(
            model_name='agency',
            name='tursab_document',
            field=models.FileField(blank=True, null=True, upload_to='agencies/tursab/', verbose_name='TÜRSAB İşletme Belgesi'),
        ),
        migrations.AddField(
            model_name='agency',
            name='tursab_group',
            field=models.CharField(blank=True, choices=[('A', 'A Grubu'), ('B', 'B Grubu'), ('C', 'C Grubu')], max_length=1, null=True, verbose_name='Acenta Grubu'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='business_type',
            field=models.CharField(choices=[('acenta', 'Tur Acentası'), ('restoran', 'Restoran'), ('kafe', 'Kafe'), ('shuttle', 'Shuttle / Transfer'), ('her_ikisi', 'Tur Acentası + Restoran/Kafe')], default='acenta', max_length=20, verbose_name='İşletme Türü'),
        ),
    ]
