# Generated by Django 4.2.29 on 2026-08-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0012_backfill_agency_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningreservation',
            name='combo_group',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Combo Grubu'),
        ),
    ]
