# Generated by Django 4.2.29 on 2026-08-02 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0013_diningreservation_combo_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_iban', models.CharField(max_length=32)),
                ('proposed_bank_account_holder', models.CharField(max_length=255)),
                ('proposed_bank_name', models.CharField(blank=True, max_length=255)),
                ('previous_iban', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('pending', 'İncelemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_change_requests', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Banka Bilgisi Değişiklik Talebi',
                'verbose_name_plural': 'Banka Bilgisi Değişiklik Talepleri',
                'ordering': ['-requested_at'],
            },
        ),
    ]
