# Generated by Django 4.2.29 on 2026-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0014_bankaccountchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentfinanceledger',
            name='entry_type',
            field=models.CharField(choices=[('sale', 'Satış Hakedişi'), ('refund', 'İade Kesintisi'), ('adjustment', 'Manuel Düzeltme'), ('payout', 'Hakediş Ödemesi')], default='sale', max_length=20),
        ),
    ]
