# Generated by Django 4.2.29 on 2026-08-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0015_alter_agentfinanceledger_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentfinanceledger',
            name='booking_ref',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
