# Generated by Django 4.2.29 on 2026-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('tour', 'Tour'), ('meal', 'Meal')], default='tour', max_length=20),
        ),
    ]
