# Generated by Django 4.2.29 on 2026-07-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_service_type'),
        ('shuttles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='booking',
            name='shuttle_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='shuttles.shuttleroute'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('tour', 'Tour'), ('meal', 'Meal'), ('shuttle', 'Shuttle')], default='tour', max_length=20),
        ),
    ]
