# Generated by Django 4.2.29 on 2026-07-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_guest_email_booking_guest_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
    ]
