# Generated by Django 4.2.29 on 2026-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_checked_in_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review_invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
