# Generated by Django 4.2.29 on 2026-08-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_combo'),
        ('bookings', '0009_booking_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tours.combo'),
        ),
        migrations.AddField(
            model_name='booking',
            name='combo_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('tour', 'Tour'), ('meal', 'Meal'), ('shuttle', 'Shuttle'), ('combo', 'Combo')], default='tour', max_length=20),
        ),
    ]
