# Generated by Django 4.2.29 on 2026-08-01 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0001_initial'),
        ('bookings', '0010_booking_combo_booking_combo_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='spa_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='spas.spaservice'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('tour', 'Tour'), ('meal', 'Meal'), ('shuttle', 'Shuttle'), ('spa', 'Spa'), ('combo', 'Combo')], default='tour', max_length=20),
        ),
    ]
