export const TOUR_DATA = {
    kapadokya: {
        id: 'kapadokya',
        title: 'Kapadokya Balon & Peri Bacaları',
        location: 'Nevşehir, Türkiye',
        rating: '4.9',
        reviews: '520',
        originalPrice: '3.200',
        price: 2400,
        discount: '%25',
        fomoCount: 14,
        duration: '3 Gün, 2 Gece',
        guide: 'Türkçe, İngilizce',
        accommodation: '5 Yıldızlı Mağara Otel',
        transportation: 'VIP Transfer Dahil',
        imageMain: 'https://images.unsplash.com/photo-1596395819057-afbf19aff3fb?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1643194553229-231a4c8a2dd9?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1534008897995-27a23e859048?fit=crop&w=600&q=80',
        description: "Kapadokya'nın büyüleyici atmosferinde, sabahın ilk ışıklarıyla havalanan yüzlerce renkli sıcak hava balonunu izlerken, mistik peri bacalarının arasında kaybolacaksınız.",
        included: ['Özel Mağara Otelinde 2 Gece Konaklama', 'Profesyonel Tur Rehberi', 'Sabah Kahvaltıları'],
        excluded: ['Öğle Yemekleri', 'Kişisel Harcamalar', 'Balon Uçuşu'],
        category: 'culture, romantic, history',
        translations: {
            'en-US': {
                title: 'Cappadocia Hot Air Balloon & Fairy Chimneys',
                location: 'Nevsehir, Turkey',
                duration: '3 Days, 2 Nights',
                guide: 'English, Turkish',
                accommodation: '5-Star Cave Hotel',
                transportation: 'VIP Transfer Included',
                description: 'Lose yourself among mystical fairy chimneys while watching hundreds of colorful hot air balloons take off at the first light of dawn in the enchanting atmosphere of Cappadocia.',
                included: ['2 Nights in Premium Cave Hotel', 'Pro Tour Guide', 'Daily Breakfasts'],
                excluded: ['Lunches', 'Personal Expenses', 'Balloon Flight (Optional)']
            },
            'de-DE': {
                title: 'Kappadokien Heißluftballon & Feenkamine',
                location: 'Nevsehir, Türkei',
                duration: '3 Tage, 2 Nächte',
                guide: 'Deutsch, Türkisch',
                accommodation: '5-Sterne Höhlenhotel',
                transportation: 'Inklusive VIP-Transfer',
                description: 'Verlieren Sie sich zwischen mystischen Feenkaminen, während Sie hunderte von bunten Heißluftballons im ersten Morgenlicht über Kappadokien aufsteigen sehen.',
                included: ['2 Nächte im Premium Höhlenhotel', 'Professioneller Reiseleiter', 'Tägliches Frühstück'],
                excluded: ['Mittagessen', 'Zusätzliche Ausgaben', 'Ballonfahrt (Optional)']
            },
            'zh-CN': {
                title: '卡帕多奇亚热气球与仙人烟囱 (VIP私人定制)',
                location: '内夫谢希尔，土耳其',
                duration: '3天2晚',
                guide: '中文，土耳其语',
                accommodation: '五星豪华洞穴酒店',
                transportation: '含VIP商务车接送',
                description: '在卡帕多奇亚迷人的氛围中，在清晨的第一缕阳光下，看着数百个五彩斑斓的热气球升空，迷失在神秘的仙女烟囱中。专为尊贵宾客定制的绝佳摄影体验。',
                included: ['2晚顶级洞穴酒店住宿', '全程资深中文向导', '每日高级早餐'],
                excluded: ['午餐', '个人消费', '热气球飞行体验（可代订）']
            }
        }
    },
    'buyuk-italya': {
        id: 'buyuk-italya',
        title: 'Büyük İtalya Turu',
        location: 'Roma, İtalya',
        rating: '4.8',
        reviews: '815',
        originalPrice: '25.000',
        price: 18150,
        discount: '%27',
        fomoCount: 32,
        duration: '7 Gün, 6 Gece',
        guide: 'Türkçe, İtalyanca',
        accommodation: '4 ve 5 Yıldızlı Oteller',
        transportation: 'Lüks Tur Otobüsü',
        imageMain: 'https://images.unsplash.com/photo-1541432901042-2b8cbc77d2a8?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1516483638261-f40af5bea098?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1502602898657-3e90760081d5?fit=crop&w=600&q=80',
        description: "Roma'nın tarihi sokaklarından Venedik'in romantik kanallarına, Floransa'nın sanat dolu meydanlarından Milano'ya kadar unutulmaz bir İtalya rüyası sizi bekliyor.",
        included: ['Tüm Konaklamalar', 'Ulaşım', 'Rehberlik'],
        excluded: ['Öğle Yemekleri', 'Vize Ücretleri'],
        category: 'culture, history, city',
        filmedIn: 'Portobello (HBO) & Sandokan (Netflix)',
    },
    'maldivler-ruyasi': {
        id: 'maldivler-ruyasi',
        title: 'Maldivler Rüyası',
        location: 'Malé, Maldivler',
        rating: '5.0',
        reviews: '340',
        originalPrice: '45.000',
        price: 39500,
        discount: '%12',
        fomoCount: 8,
        duration: '5 Gün, 4 Gece',
        guide: 'İngilizce',
        accommodation: 'Su Üzeri Bungalov',
        transportation: 'Deniz Uçağı Transferi',
        imageMain: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?fit=crop&w=600&q=80',
        description: "Turkuaz suların üzerinde lüks bir yaşam. Hayatınızın en rahatlatıcı ve romantik tatili.",
        included: ['Tam Pansiyon Konaklama', 'Transferler', 'Hoşgeldin Paketi'],
        excluded: ['Uluslararası Uçuşlar', 'Ekstra Turlar'],
        category: 'beach, romantic, relax',
    },
    'japonya-bahar': {
        id: 'japonya-bahar',
        title: 'Japonya Bahar (Sakura)',
        location: 'Tokyo, Japonya',
        rating: '4.9',
        reviews: '120',
        originalPrice: '62.000',
        price: 58000,
        discount: '%6',
        fomoCount: 22,
        duration: '10 Gün, 9 Gece',
        guide: 'Türkçe, Japonca',
        accommodation: 'Oteller ve Ryokan',
        transportation: 'Hızlı Tren (Shinkansen)',
        imageMain: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?fit=crop&w=600&q=80',
        description: "Kiraz çiçekleri altında benzersiz bir kültür turu.",
        included: ['Ulaşım', '10 Gece Konaklama', 'Rehberlik'],
        excluded: ['Öğle Yemekleri', 'Vize'],
        category: 'culture, nature, asian',
        filmedIn: 'Alice in Borderland S3 (Netflix)',
    },
    'iskandinav-fiyort': {
        id: 'iskandinav-fiyort',
        title: 'İskandinav Fiyortları ve Kuzey Işıkları',
        location: 'Tromso, Norveç',
        rating: '4.8',
        reviews: '210',
        originalPrice: '40.000',
        price: 36000,
        discount: '%10',
        fomoCount: 45,
        duration: '6 Gün, 5 Gece',
        guide: 'Türkçe, İngilizce',
        accommodation: 'Cam İglo Oteller',
        transportation: 'Lüks Minibüs',
        imageMain: 'https://images.unsplash.com/photo-1531366936337-778f6f6916fa?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1502481851512-e9e2529bfbf9?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1521639736-24e52549aef5?fit=crop&w=600&q=80',
        description: "Dünyanın en büyüleyici doğa olayı Kuzey Işıklarını fiyortların eşsiz sessizliğinde deneyimleyin.",
        included: ['Konaklama', 'Kuzey Işıkları Avı Turu', 'Husky Kızak Turu'],
        excluded: ['Uluslararası Uçuşlar', 'Akşam Yemekleri'],
        category: 'nature, adventure, winter',
    },

    // GASTORONOMİ & GÜNÜBİRLİK DENEYİM
    'napoli-pizza-atolyesi': {
        id: 'napoli-pizza-atolyesi',
        title: 'Napoli Pizza ve Tiramisu Atölyesi',
        location: 'Napoli, İtalya',
        rating: '4.9',
        reviews: '1240',
        originalPrice: '3.500',
        price: 2850,
        discount: '%18',
        fomoCount: 85,
        duration: '4 Saat',
        guide: 'İngilizce, İtalyanca',
        accommodation: 'Konaklamasız (Günübirlik Yalnızca Deneyim)',
        transportation: 'Mekanda Buluşma',
        imageMain: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1555072956-7758afb20e8f?fit=crop&w=600&q=80',
        description: "Geleneksel bir Napoli pizzacısında yerel şeflerden gerçek Margherita pizzası ve otantik Tiramisu yapımını öğrenin. Öğle yemeği ve şarap tadımı dahildir.",
        included: ['Pizza ve Tiramisu Atölyesi', 'Sınırsız Şarap ve Meşrubat', 'Şef Önlüğü', 'Tur Sonu Öğle Yemeği'],
        excluded: ['Otele Transfer', 'Ekstra Harcamalar'],
        category: 'gastronomy, experience, daily',
        filmedIn: 'Portobello (HBO)',
    },
    'gaziantep-gurme': {
        id: 'gaziantep-gurme',
        title: 'Gaziantep Gurme ve Lezzet Turu',
        location: 'Gaziantep, Türkiye',
        rating: '4.9',
        reviews: '850',
        originalPrice: '12.000',
        price: 9500,
        discount: '%20',
        fomoCount: 28,
        duration: '3 Gün, 2 Gece',
        guide: 'Türkçe, İngilizce',
        accommodation: 'Butik Konaklama',
        transportation: 'Havalimanı Transferi ve Şehir İçi Ulaşım',
        imageMain: 'https://images.unsplash.com/photo-1615486171448-4ffdffcb2a54?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?fit=crop&w=600&q=80',
        description: "Dünyanın gastronomi başkentlerinden biri olan Gaziantep'te, baklavanın, kebabın ve yöresel baharatların izinde unutulmaz bir lezzet şöleni.",
        included: ['Butik Otelde 2 Gece Konaklama', 'Tüm Tadım Etkinlikleri ve Yemekler', 'Yerel Yemek Atölyesi', 'Rehberlik'],
        excluded: ['Uçak Biletleri', 'Kişisel Harcamalar'],
        category: 'gastronomy, culture',
    },

    // ADRENALIN & EKSTREM SPORLAR
    'fethiye-yama-parasutu': {
        id: 'fethiye-yama-parasutu',
        title: 'Ölüdeniz Babadağ Yamaç Paraşütü (Extrem)',
        location: 'Fethiye, Türkiye',
        rating: '5.0',
        reviews: '2100',
        originalPrice: '4.000',
        price: 3200,
        discount: '%20',
        fomoCount: 65,
        duration: '3 Saat',
        guide: 'Lisanslı Pilot Eşliğinde',
        accommodation: 'Konaklamasız (Günübirlik Deneyim)',
        transportation: 'Otelden Alma ve Bırakma Dahil',
        imageMain: 'https://images.unsplash.com/photo-1520626330055-1f6cc9e0db96?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1465492193850-8446215caeb0?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1517596825700-11234479ed3a?fit=crop&w=600&q=80',
        description: "Babadağ'ın 1960 metre zirvesinden Ölüdeniz'in muhteşem manzarasına doğru bir atlayış yapın. Tamamen güvenli ve adrenalin dolu bu deneyimi kaçırmayın.",
        included: ['Otel Transferi', 'Uçuş Öncesi Eğitim', 'Gerekli Tüm Ekipmanlar', 'Lisanslı Pilot ile Tandem Uçuş', 'Sigorta'],
        excluded: ['Video ve Fotoğraf Çekimi (Ekstra)'],
        category: 'adrenaline, extreme, daily',
    },
    'kapadokya-atv-safari': {
        id: 'kapadokya-atv-safari',
        title: 'Gün Batımı Kanyon ATV Safari',
        location: 'Kapadokya, Türkiye',
        rating: '4.8',
        reviews: '1350',
        originalPrice: '1.200',
        price: 850,
        discount: '%30',
        fomoCount: 112,
        duration: '2 Saat',
        guide: 'İngilizce, Türkçe',
        accommodation: 'Konaklamasız (Günübirlik Deneyim)',
        transportation: 'Buluşma Noktasına Ulaşım Dahil Değil',
        imageMain: 'https://images.unsplash.com/photo-1577971031750-f8f20ad10f44?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1596395819057-afbf19aff3fb?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1643194553229-231a4c8a2dd9?fit=crop&w=600&q=80',
        description: "Kapadokya'nın gizemli vadilerinde, peri bacalarının arasından süzülerek tozu dumana katacağınız heyecan verici bir ATV macerası. Kılıçlar ve Güllüdere Vadisi geçişleri.",
        included: ['2 Saatlik ATV Kiralama', 'Kask ve Güvenlik Ekipmanları', 'Rehber Öncülüğü'],
        excluded: ['Kişisel Harcamalar', 'Otel Transferi'],
        category: 'adrenaline, adventure, daily',
    },

    // ASYA / UZAK DOĞU EKLENTİSİ
    'bali-ruyasi': {
        id: 'bali-ruyasi',
        title: 'Ubud Ormanları ve Sonsuzluk Havuzları',
        location: 'Bali, Endonezya',
        rating: '4.9',
        reviews: '5230',
        originalPrice: '85.000',
        price: 64500,
        discount: '%24',
        fomoCount: 88,
        duration: '7 Gün, 6 Gece',
        guide: 'İngilizce, Çince, Türkçe',
        accommodation: '5 Yıldızlı Orman Resort',
        transportation: 'VIP Havalimanı Karşılama ve Transfer',
        imageMain: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?fit=crop&w=600&q=80',
        description: "Bali'nin mistik Ubud ormanlarında, sonsuzluk havuzlarının keyfini çıkarıp antik tapınaklarda arınma seanslarına katılacağınız ruhani ve lüks bir deneyim.",
        included: ['Resort Konaklama', 'Tapınak Turları', 'Açık Büfe Kahvaltı', '1 Kere Ücretsiz Spa'],
        excluded: ['Uluslararası Uçak Biletleri', 'Bahşişler'],
        category: 'culture, romantic, zen',
        translations: {
            'en-US': {
                title: 'Ubud Jungles & Infinity Pools VIP',
                duration: '7 Days, 6 Nights',
            },
            'zh-CN': {
                title: '乌布丛林与无边泳池 (尊享禅意之旅)',
                duration: '7天6晚',
            }
        }
    },
    'kyoto-cay': {
        id: 'kyoto-cay',
        title: 'Geleneksel Kyoto Çay Seremonisi & Zen Sanatı',
        location: 'Kyoto, Japonya',
        rating: '5.0',
        reviews: '920',
        originalPrice: '4.500',
        price: 3200,
        discount: '%28',
        fomoCount: 14,
        duration: '3 Saat',
        guide: 'İngilizce, Japonca',
        accommodation: 'Konaklamasız (Günübirlik Deneyim)',
        transportation: 'Otele Kadar Bırakma Dahil',
        imageMain: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?fit=crop&w=1200&q=80',
        imageSub1: 'https://images.unsplash.com/photo-1528164344705-47542687000d?fit=crop&w=600&q=80',
        imageSub2: 'https://images.unsplash.com/photo-1576174464184-fb78fe18dfbc?fit=crop&w=600&q=80',
        description: "Antik Kyoto'da gizli kalmış asırlık bir çay evinde, deneyimli çay üstatları eşliğinde gerçek Matcha ritüelinin huzuruna varın.",
        included: ['Çay Seremonisi ve Matcha', 'Japon Tatlıları (Wagashi)', 'Geleneksel Kimono Kiralama (İsteğe Bağlı)'],
        excluded: ['Ekstra İçecekler'],
        category: 'culture, zen, daily',
        translations: {
            'en-US': {
                title: 'Kyoto Zen Tea Ceremony',
                duration: '3 Hours',
            },
            'zh-CN': {
                title: '京都传统茶道与禅宗体验 (私人定制)',
                duration: '3 小时',
            }
        },
        filmedIn: 'Last Samurai Standing (Netflix)',
    }
};
