# Generated by Django 4.2.29 on 2026-07-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0009_booking_reminder_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=20)),
                ('recipient', models.CharField(help_text='Telefon numarası (E.164 önerilir)', max_length=32)),
                ('event_type', models.CharField(choices=[('booking_confirmed', 'booking_confirmed'), ('tour_reminder', 'tour_reminder'), ('booking_cancelled', 'booking_cancelled'), ('new_booking', 'new_booking')], max_length=40)),
                ('lang', models.CharField(default='tr', max_length=5)),
                ('body', models.TextField(help_text='Kuyruğa yazıldığı an render edilmiş nihai metin')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('sent', 'Gönderildi'), ('failed', 'Başarısız')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Bildirim Kaydı',
                'verbose_name_plural': 'Bildirim Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
