# Generated by Django 4.2.29 on 2026-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('reading_time', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=255)),
                ('author_role', models.CharField(max_length=255)),
                ('author_avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(max_length=100)),
                ('related_tour_slug', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
