# Generated by Django 4.2.29 on 2026-03-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/avatars/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/covers/'),
        ),
    ]
