# Generated by Django 4.2.29 on 2026-08-01 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0013_diningreservation_combo_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaVenue',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('image_main', models.ImageField(upload_to='spas/')),
                ('image_sub1', models.ImageField(blank=True, null=True, upload_to='spas/')),
                ('image_sub2', models.ImageField(blank=True, null=True, upload_to='spas/')),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spa_venues', to='agencies.agency')),
            ],
        ),
        migrations.CreateModel(
            name='SpaService',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('min_guests', models.IntegerField(default=1)),
                ('max_guests', models.IntegerField(default=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='spas/')),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='spas.spavenue')),
            ],
        ),
        migrations.CreateModel(
            name='SpaAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('max_capacity', models.IntegerField(default=8)),
                ('booked_count', models.IntegerField(default=0)),
                ('spa_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='spas.spaservice')),
            ],
            options={
                'verbose_name_plural': 'Spa Availabilities',
                'ordering': ['date', 'time'],
                'unique_together': {('spa_service', 'date', 'time')},
            },
        ),
    ]
