# Generated by Django 4.2.29 on 2026-07-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0010_menu_file_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleRoute',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('minivan', 'Minivan'), ('minibus', 'Minibüs'), ('bus', 'Otobüs')], default='minivan', max_length=20)),
                ('capacity', models.IntegerField(default=8)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_passengers', models.IntegerField(default=1)),
                ('max_passengers', models.IntegerField(default=8)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('image_main', models.ImageField(upload_to='shuttles/')),
                ('image_sub1', models.ImageField(blank=True, null=True, upload_to='shuttles/')),
                ('image_sub2', models.ImageField(blank=True, null=True, upload_to='shuttles/')),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shuttle_routes', to='agencies.agency')),
            ],
        ),
        migrations.CreateModel(
            name='ShuttleAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('max_capacity', models.IntegerField(default=8)),
                ('booked_count', models.IntegerField(default=0)),
                ('shuttle_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='shuttles.shuttleroute')),
            ],
            options={
                'verbose_name_plural': 'Shuttle Availabilities',
                'ordering': ['date', 'time'],
                'unique_together': {('shuttle_route', 'date', 'time')},
            },
        ),
    ]
