# Generated by Django 4.2.29 on 2026-03-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('fomo_count', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=100)),
                ('guide', models.CharField(max_length=255)),
                ('accommodation', models.CharField(blank=True, max_length=255, null=True)),
                ('transportation', models.CharField(blank=True, max_length=255, null=True)),
                ('image_main', models.URLField(max_length=500)),
                ('image_sub1', models.URLField(blank=True, max_length=500, null=True)),
                ('image_sub2', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('filmed_in', models.CharField(blank=True, max_length=255, null=True)),
                ('included', models.JSONField(blank=True, default=list)),
                ('excluded', models.JSONField(blank=True, default=list)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='agencies.agency')),
            ],
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_steps', to='tours.tour')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
