# Generated by Django 4.2.29 on 2026-03-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image_main',
            field=models.ImageField(upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_sub1',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_sub2',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
