# Generated by Django 4.2.29 on 2026-07-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_category_tour_category_obj_touravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='touravailability',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='touravailability',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
