# Generated by Django 4.2.29 on 2026-07-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_touravailability_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cancellation_policy',
            field=models.CharField(choices=[('flexible', 'Esnek'), ('moderate', 'Orta'), ('strict', 'Katı')], default='flexible', max_length=20),
        ),
    ]
