# Generated by Django 4.2.29 on 2026-08-01 16:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0013_diningreservation_combo_group'),
        ('tours', '0005_tour_cancellation_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='agencies.menu')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='tours.tour')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
